// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/schedule_repository.go

package mock

import (
	"context"
	"go-futsal-booking-api/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScheduleRepository) Create(ctx context.Context, schedule *domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleRepositoryMockRecorder) Create(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleRepository)(nil).Create), ctx, schedule)
}

// Delete mocks base method.
func (m *MockScheduleRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduleRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduleRepository)(nil).Delete), ctx, id)
}

// FindByFieldID mocks base method.
func (m *MockScheduleRepository) FindByFieldID(ctx context.Context, fieldID uint) ([]domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFieldID", ctx, fieldID)
	ret0, _ := ret[0].([]domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFieldID indicates an expected call of FindByFieldID.
func (mr *MockScheduleRepositoryMockRecorder) FindByFieldID(ctx, fieldID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFieldID", reflect.TypeOf((*MockScheduleRepository)(nil).FindByFieldID), ctx, fieldID)
}

// FindByID mocks base method.
func (m *MockScheduleRepository) FindByID(ctx context.Context, id uint) (domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockScheduleRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockScheduleRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockScheduleRepository) Update(ctx context.Context, schedule *domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduleRepositoryMockRecorder) Update(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduleRepository)(nil).Update), ctx, schedule)
}
